export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_LOADED = "POSTS_LOADED";
export const POST_LOADED = "POST_LOADED";
